name: test_weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  intl: ^0.19.0
  weather: ^3.1.1
  equatable: ^2.0.5
  path_provider: ^2.1.3
  shared_preferences: ^2.2.2
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.10+1
  bloc_concurrency: ^0.2.3
  go_router: ^14.3.0

  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  formz: ^0.8.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/image/images/
    - assets/image/icons/
